// let fname = prompt("Enter your first name");
// let lname = prompt("Enter your last name");
// console.log(fname + " "  +  lname);
// let phone = prompt("What is your favorite phone");
// document.write("My favorite phone is : " + phone + "<br>");
// // document.write("Length of string : " + phone.length);
// let country = "Pakistani";
// document.write("String: " + country + "<br>");
// document.write("Index of n: " + country.indexOf("n"));
// let country ="Hello world";
// document.write("String: " + country + "<br>");
// document.write("Last index of n: " + country.lastIndexOf("l"));
//  let country = "Pakistani";
//  document.write("String: " + country + "<br>");
//  document.write("Index of n: " + country.charAt(3));
        // let _String = "Hyderabad";
        // let String = _String.replace("Hyder", "Islam");
        // document.write("City : " + _String + "<br>");
        // document.write("After Replacement : " + String);
        // var message = "Ali and Sami are best friends. They play cricket and football together.";
        // var updatedMessage = message.replace(/and/g, "&");
        // document.write("<h1>Message:</h1>");
        // document.write("<p>" + updatedMessage + "</p>");        
// let str = "472";
// let num = Number(str);
// document.write("String value: " + str + "<br>" + " type: " + typeof str + "<br>");
// document.write("Number value: " + num + "<br>" + " type: " + typeof num + "<br>");
// let case_ = "peanuts";
// let case__ = case_.toUpperCase();
// document.write("User Input : " + case_ + "<br>");
// document.write("Upper case : " + case__);
// let _case = "javascript";
// let case____ = ToTitleCase(_case);
// document.write("User Input : " + _case + "<br>");
// document.write("Title case : " + case____);
// var num = 35.36;
// var str = num.toString();
// var result = str.replace('.', '');
// document.getElementById('convertedValue').innerHTML = "Converted value: " + result;
// let split_ = "University of karachi"
// let as = split_.split("");
// console.log(as);
let country = "Pakistan";
let country_ = country.lastIndexOf()